### ISSUE TITLE
Enviroment

### ISSUE THREAD

**Issue by nambui2000k** [ConnectyCube/connectycube-flutter-samples#165]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[x] Android
[x] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
What is the difference between CubeEnvironment.PRODUCTION and CubeEnvironment.DEVELOPMENT? 
When develop i can use CubeEnvironment.PRODUCTION?

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment]
Initially, it was added to separate Test builds and Release builds for testing notifications. But a lot of our customers were mistaken with configurations in these environments and we decided to deprecate this feature. At this moment the push notification will be sent to both environments.

**Comment by cybex-dev** [comment]
> Initially, it was added to separate Test builds and Release builds for testing notifications. But a lot of our customers were mistaken with configurations in these environments and we decided to deprecate this feature. At this moment the push notification will be sent to both environments.

Last time I worked with the environment, had some trouble as I had forgotten about this setting - further there are 3 places to change the environment. @nambui2000k the environment makes a difference for iOS as iOS has sandbox/production APNS and it matters from where the notification comes. e.g. If you release an app with development mode set (i.e. sandbox APNS is used), no notifications will work, VoIP or otherwise.
