### ISSUE TITLE
Does ConnectyCube Support Huawei Push Notifications ? 

### ISSUE THREAD

**Issue by jostney** [ConnectyCube/connectycube-flutter-samples#242]
Clear question, is it possible to send chat push notifications to Huawei devices ?

In ConnectyCube dashboard i only see APN and FCM.

**Comment by DaveLomber** [comment]
@jostney currently only APNS (both certificate and JWT based communication) and FCM providers are supported.

Because of low demand in Huawei Push Notifications in  ConnectyCube - there is no much work conducted on this matter except R&D on the Huawei Push Notifications API which seems pretty close to FCM.

Please contact at support@connectycube.com if you have more importance on this matter
