### ISSUE TITLE
Seeking Guidance on Enhancing Video Quality and Layout in Flutter Video Calling App

### ISSUE THREAD

**Issue by Video23** [ConnectyCube/connectycube-flutter-samples#312]
Hello,

We are currently utilizing the Flutter examples for our video calling application. While the stability is excellent, we've noticed that the video quality is not up to our expectations. (very low) Is there a way to enhance the video quality?

Additionally, we are interested in having a dual video screen layout, featuring one large and one small video screen, similar to the layout shown on th eflutter examples page
Could anyone provide guidance or suggestions on how to achieve these improvements?

Thank you very much for your assistance!

**Comment by TatankaConCube** [comment]
please specify first, what technology you are using, is it the P2P calls or Conferences?

**Comment by Video23** [comment]
Currently, we are focusing on one-to-one calls, but we plan to implement conference calls in the future.

**Comment by TatankaConCube** [comment]
the Connectycube platform supports two types of connection between users, there is a comparison of them https://connectycube.com/2020/04/15/connectycube-calling-api-comparison/

To increasing the video quality in P2P try the next:
- set the resolution for the video according to this documentation https://developers.connectycube.com/flutter/videocalling?id=media-stream-configurations
- set the maximum bandwidth according to this documentation https://developers.connectycube.com/flutter/videocalling?id=call-quality for example to 2048Kbit/s
But pay attention, the WebRTC technology can adapt the stream due to network speed or the device performance.

To increase the video quality in the Conferences try the next:
- set the maximum bandwidth `_callSession.setMaxBandwidth(0)` to the 0 for disabling any limits for your conversation on the server side. do it immediately after succes jouining to the call;
- request the stream with maximum quality for your opponent using the next code `_callSession.requestPreferredStreamsForOpponent(userId, StreamType.high)`. you can do it after receiving the media stream from the opponent;
In these cases the server will try to send the stream with the maximum possible quality to your opponents.

> eflutter examples

could you please provide the screenshot of what you mean?

Currently, we are working on the feature for adding more than one video track for user and this feature will be presented in the next version of our SDK, but in the current realisation we don't provide the possibility for requesting the quality for streams separately.

**Comment by Video23** [comment]
Thank you for your prompt and comprehensive response. The details you provided about enhancing video quality in both P2P and conference calls are incredibly helpful!
We're absolutely going to work on this 

I've attached a screenshot to clarify what we're aiming for:
![image](https://github.com/ConnectyCube/connectycube-flutter-samples/assets/148527883/b4acf7e6-7db2-4a1e-b71e-03d4b16255df)

**Comment by TatankaConCube** [comment]
> I've attached a screenshot

you will have this layout mode in the P2P calls sample in case you have only one opponent in the call (private calls).

**Comment by Video23** [comment]
Thank You for your help. We're using the examples but only getting a 50/50 split screen. Is it possible to give me a link to the right example flutter file with this layout?

**Comment by Video23** [comment]
Sure, I'll pull the latest changes from the 'master' branch and will keep you informed this weekend 

Thank you so much for your help and tips ! 

Hope we will achieve to get the above layout

**Comment by Video23** [comment]
Thank you very much! With your assistance, we successfully achieved the enhanced layout, and the quality has significantly improved as well
