### ISSUE TITLE
Notifications send to all attendees [even the host]

### ISSUE THREAD

**Issue by radyhaggag** [ConnectyCube/connectycube-flutter-samples#326]
**Specify the sample to which the issue belongs (use [x]):**

[] Conference Calls sample

**Platform (use [x])**
[] Android
[] iOS

**Describe the bug:**
I'm working video call feature and on each meeting there are two users [tutor, student] when anyone create a meeting the notification is go to all users, so it must go only to others not the creator of the meeting.

i tried to handle the notifications but i cannot control the receiver. 

**Actual result:**
the notification is go to all users.

**Expected behavior:**
The notification should go to only the other attendees without the host or the creator.

**Comment by TatankaConCube** [comment]
it is an expected behavior. when you send the system message throw API request the server doesn't know your currend resource_id and sends message to all logged in devices (the Carbon messages feature is enabled by default). you have few otions here:
1. ignore own messages on the receiver side (if you don't support multidevice feature in your app) as we do in our sample [here](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/conf_call_sample/lib/src/managers/call_manager.dart#L72);
2. use the chat connection for sending the system messages instead of API requests https://developers.connectycube.com/flutter/messaging?id=system-messages
