### ISSUE TITLE
CubeChatConnection.instance.login takes 5 to 6 seconds

### ISSUE THREAD

**Issue by wrteam-priyansh** [ConnectyCube/connectycube-flutter-samples#47]

**Comment by TatankaConCube** [comment]
there [topic ](https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/12) about your question

**Comment by shivanijha002** [comment]
CubeChatConnection.instance.login is taking 6-15 seconds for me even with 100mbps internet connectivity. This is experienced by all of my app user. I am getting negative feedback of app just because of this slowness. Kindly help to optimize login experience.

Below is the code snippet used:
 await createSession(user).then(
      (cubeSession) async {
                    if (!CubeSessionManager.instance.isActiveSessionValid()) {
                         print('Session Invalid');
                    } 
                   else  {
                          if (CubeChatConnection.instance.chatConnectionState !=
                                        CubeChatConnectionState.Ready) {
                                      print("Log: Login start" + DateTime.now().toString());
                                      await CubeChatConnection.instance
                                          .login(user1)
                                          .then((cubeUser) async {
                                        print("Log: Login end" + DateTime.now().toString());
                                        print(cubeUser);
                                      }).catchError((error) {
                                        print("Login error $error");
                                      });
                                    }
})
